// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NurseryApp.Data;

namespace NurseryApp.Migrations.NurseryDb
{
    [DbContext(typeof(NurseryDbContext))]
    partial class NurseryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NurseryApp.Models.Basket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("NurseryApp.Models.BasketProduct", b =>
                {
                    b.Property<int>("BasketID");

                    b.Property<int>("ProductID");

                    b.Property<int>("Quantity");

                    b.HasKey("BasketID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("NurseryApp.Models.Checkout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Total");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("NurseryApp.Models.CheckoutProduct", b =>
                {
                    b.Property<int>("CheckoutID");

                    b.Property<int>("ProductID");

                    b.Property<int>("Quantity");

                    b.HasKey("CheckoutID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("CheckoutProducts");
                });

            modelBuilder.Entity("NurseryApp.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bulk");

                    b.Property<string>("Description");

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("Sku");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Ranier Cherry Tree",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "abcdef",
                            Type = 0
                        },
                        new
                        {
                            ID = 2,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Yoshino Cherry Tree",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "qwerty",
                            Type = 0
                        },
                        new
                        {
                            ID = 3,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Rhododendron",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "123345",
                            Type = 1
                        },
                        new
                        {
                            ID = 4,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Dwarf Apple Tree",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "yuiop",
                            Type = 0
                        },
                        new
                        {
                            ID = 5,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Dwarf Plum Tree",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "567ghj",
                            Type = 0
                        },
                        new
                        {
                            ID = 6,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Red Raspberry",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "098lkjh",
                            Type = 1
                        },
                        new
                        {
                            ID = 7,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Echivera",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "zxcv34",
                            Type = 3
                        },
                        new
                        {
                            ID = 8,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Magestic Palm",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "9d9emd",
                            Type = 3
                        },
                        new
                        {
                            ID = 9,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "California Black Oak",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "098asdf",
                            Type = 0
                        },
                        new
                        {
                            ID = 10,
                            Bulk = false,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Giant Sunflower",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "abci876k",
                            Type = 2
                        },
                        new
                        {
                            ID = 11,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Ranier Cherry Tree - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "abcdef",
                            Type = 0
                        },
                        new
                        {
                            ID = 12,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Yoshino Cherry Tree - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "qwerty",
                            Type = 0
                        },
                        new
                        {
                            ID = 13,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Rhododendron - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "123345",
                            Type = 1
                        },
                        new
                        {
                            ID = 14,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Dwarf Apple Tree - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "yuiop",
                            Type = 0
                        },
                        new
                        {
                            ID = 15,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Dwarf Plum Tree - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "567ghj",
                            Type = 0
                        },
                        new
                        {
                            ID = 16,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Red Raspberry - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "098lkjh",
                            Type = 1
                        },
                        new
                        {
                            ID = 17,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Echivera- Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "zxcv34",
                            Type = 3
                        },
                        new
                        {
                            ID = 18,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Magestic Palm - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "9d9emd",
                            Type = 3
                        },
                        new
                        {
                            ID = 19,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "California Black Oak - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "098asdf",
                            Type = 0
                        },
                        new
                        {
                            ID = 20,
                            Bulk = true,
                            Description = "Placeholder Description",
                            Img = "https://images.pexels.com/photos/1002703/pexels-photo-1002703.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Name = "Giant Sunflower - Bulk",
                            Price = 1.00m,
                            Quantity = 0,
                            Sku = "abci876k",
                            Type = 2
                        });
                });

            modelBuilder.Entity("NurseryApp.Models.BasketProduct", b =>
                {
                    b.HasOne("NurseryApp.Models.Basket")
                        .WithMany("BasketProducts")
                        .HasForeignKey("BasketID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NurseryApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NurseryApp.Models.CheckoutProduct", b =>
                {
                    b.HasOne("NurseryApp.Models.Checkout")
                        .WithMany("CheckoutProducts")
                        .HasForeignKey("CheckoutID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NurseryApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
